# Render Blueprint (Lite-Node Deployment)
services:
  - type: web
    name: stacy-ai-premium
    env: node
    rootDir: stacy
    branch: main
    plan: free
    buildCommand: "npm install --production"
    startCommand: "node server.js"
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 10000
      - key: IS_RENDER
        value: "true"
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      # เจ้านายใส่ค่าที่เหลือในพอร์ทัลเหมือนเดิมนะคะ

  - type: web
    name: vecna-music-bot
    env: node
    rootDir: vecna
    branch: main
    plan: free
    buildCommand: "npm install --production"
    startCommand: "node server.js"
    envVars:
      - key: PORT
        value: 3000
